# Generated by Django 5.2.3 on 2025-07-15 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apl_euphoria', '0002_venta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='id_categoria',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='id_marca',
            new_name='marca',
        ),
        migrations.RemoveField(
            model_name='promocion',
            name='producto',
        ),
        migrations.AddField(
            model_name='promocion',
            name='id_producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apl_euphoria.producto'),
            preserve_default=False,
        ),
    ]
