# Generated by Django 5.2.4 on 2025-07-15 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apl_euphoria', '0003_rename_id_categoria_producto_categoria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='id_cliente',
            new_name='cliente',
        ),
    ]
