# Generated by Django 5.2.3 on 2025-07-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apl_euphoria', '0003_rename_id_categoria_producto_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marcacosmetico',
            name='nombre',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
