# Generated by Django 5.2.4 on 2025-07-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apl_euphoria', '0004_rename_id_cliente_pedido_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha',
            field=models.DateField(),
        ),
    ]
