# Generated by Django 5.2.4 on 2025-07-16 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apl_euphoria', '0004_marcacosmetico_nombre'),
        ('apl_euphoria', '0005_alter_pedido_fecha'),
    ]

    operations = [
    ]
